### PR TITLE
Update GameManager.cs #45

### PR DESCRIPTION
**Pull request by mikebarrett19**
see #45

### CODE REVIEW

**Comment by Mikou27** [comment]
Hi, that's very interesting and it's among the most requested features/changes. I'm not familiar with assemblies for now, so i will have to take the time ro review it correctly. Maybe we could get in touch if you're interested at contributing more to the project? EDIT:  I forgot to ask you if you have finally got it to work the way you want with Playnite.

**Comment by Snailedlt** [comment]
@mikebarrett19 did you get it working with playnite? :)

**Comment by mikebarrett19** [comment]
@Mikou27 @Snailedlt Sorry y'all, work has been busy and your messages got lost. I haven't gotten it to work with playnite, it wasn't as "drop in" as I thought it would be, as so much of the configuration is based in the gui. I plan to take another crack at it one of these days, I'll probably need to contribute default controller to screen mappings or something. It's up to you guys what to do with this pull request. We could close it until I get something working in playnite. I doubt I'll get to it until at least this summer. I'm not a C# developer by trade, but I plan on using contributions to this and playnite to learn C# in my free time. I need the assembly source changed because when I run nucleus dlls from another application (playnite) the directories are incorrect because they're sourced from the main application. But since I'm new to C# and windows development in general I have no idea the implications of this change, just that it fixes the directory problem. I can look into other fixes if this causes some issues. Appreciate y'all!

**Comment by Snailedlt** [comment]
I'm not actively working on the project, so @Mikou27 should decide what to do with the PR :)

**Pull request closed without merging**
